Repository humanprotocol/human-protocol, pull requests merged in 2023-11, with the labels that each got.

#1156 feature: better profanity filter
  packages/examples/fortune/recording-oracle/package.json
  packages/examples/fortune/recording-oracle/src/plugins/config.ts
  packages/examples/fortune/recording-oracle/src/plugins/curses.ts
  packages/examples/fortune/recording-oracle/src/services/recordingOracle.ts
  yarn.lock
Labels: WIP

#1191 Hufi - fix Exchange Oracle return liquidity value
  packages/apps/hufi/exchange-oracle/server/src/modules/job/job.controller.ts
  packages/apps/hufi/exchange-oracle/server/src/modules/job/job.dto.ts
  packages/apps/hufi/exchange-oracle/server/src/modules/job/job.service.ts
Labels: Oracles

#1202 [Reputation Oracle] Modify event name for incoming webhooks
  packages/apps/reputation-oracle/server/src/common/enums/webhook.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: Oracles

#1207 [Reputation Oracle] Update absolute paths to run on Vercel
  packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
Labels: Oracles

#1221 Job Launcher - Fix results endpoint
  packages/apps/job-launcher/server/src/modules/job/job.dto.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: bug

#1222 [Job Launcher] Show job results in job details
  packages/apps/job-launcher/client/src/hooks/useJobDetails.ts
  packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
  packages/apps/job-launcher/client/src/services/job.ts
  packages/apps/job-launcher/client/src/types/index.ts
Labels: Oracles

#1169 [Job Launcher][Reputation Oracle] Oracles bugs
  packages/apps/fortune/recording-oracle/src/common/utils/curseWords.ts
  packages/apps/job-launcher/server/src/common/utils/status.ts
  packages/apps/job-launcher/server/src/database/migrations/1699276318295-AddJobCompletedStatus.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
  packages/apps/reputation-oracle/server/.env.example
  packages/apps/reputation-oracle/server/src/common/config/env.ts
  packages/apps/reputation-oracle/server/src/database/migrations/1699287419841-uniqueEntryWehbookIncoming.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.entity.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
  packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/escrow.ts
Labels: SDK

#1227 Job Launcher Client - mainnet restrictions
  packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
  packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
  packages/apps/job-launcher/client/src/constants/chains.ts
Labels: Oracles

#1232 [Job Launcher] Set address as env variable and check receiver in crypto paymets
  packages/apps/job-launcher/client/src/components/Jobs/Create/CryptoPayForm.tsx
  packages/apps/job-launcher/client/src/components/TopUpAccount/CryptoTopUpForm.tsx
  packages/apps/job-launcher/client/src/constants/addresses.ts
  packages/apps/job-launcher/client/src/vite-env.d.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
Labels: Oracles

#1248 [Job Launcher] Fix failing tests in Payment module
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
Labels: Oracles

#1223 [Job Launcher] Make the url of CVAT results clickable
  packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
Labels: Oracles

#1277 All oracles - Google Storage cache
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
  packages/apps/hufi/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
  packages/examples/fortune/launcher/server/src/plugins/s3.ts
  packages/examples/fortune/recording-oracle/src/plugins/s3.ts
  packages/examples/fortune/reputation-oracle/src/services/s3.ts
  packages/sdk/typescript/human-protocol-sdk/src/storage.ts
  packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts
Labels: Oracles

#1292 Fix and clean oracles
  packages/apps/fortune/exchange-oracle/server/.env.example
  packages/apps/fortune/exchange-oracle/server/src/common/config/env.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
  packages/apps/fortune/exchange-oracle/server/test/constants.ts
  packages/apps/fortune/recording-oracle/src/common/config/server.ts
  packages/apps/fortune/recording-oracle/src/common/config/validation.ts
  packages/apps/fortune/recording-oracle/src/main.ts
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/docker-compose.yml
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/modules/job/job.repository.ts
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow/escrow_client.py
Labels: Oracles
