Repository humanprotocol/human-protocol, pull requests merged in 2023-08, with the labels that each got.

#739 [CVAT][Recording Oracle] Added `alembic upgrade head` command to `start_dev.sh` script
  packages/examples/cvat/recording-oracle/bin/start_dev.sh
Labels: 0.5

#752 Fixed path in `ci-test-cvat-eo.yaml` action
  .github/workflows/ci-test-cvat-eo.yaml
Labels: bug, CVAT, 0.5

#754 Updated dependencies in CVAT Exchange Oracle and Recording Oracles
  packages/examples/cvat/exchange-oracle/docker-compose.test.yml
  packages/examples/cvat/exchange-oracle/poetry.lock
  packages/examples/cvat/exchange-oracle/src/validators/signature.py
  packages/examples/cvat/exchange-oracle/tests/api/modules/oracle_webhook/test_jl_webhook.py
  packages/examples/cvat/exchange-oracle/tests/integration/modules/chain/test_web3.py
  packages/examples/cvat/exchange-oracle/tests/utils/constants.py
  packages/examples/cvat/recording-oracle/poetry.lock
Labels: WIP, CVAT

#773 [CVAT][Recording Oracle] Integration tests for cron jobs
  packages/examples/cvat/recording-oracle/docker-compose.test.yml
  packages/examples/cvat/recording-oracle/src/config.py
  packages/examples/cvat/recording-oracle/src/constants.py
  packages/examples/cvat/recording-oracle/src/modules/chain/web3.py
  packages/examples/cvat/recording-oracle/src/modules/webhook/jobs/process_exchange_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/integration/modules/chain/test_web3.py
  packages/examples/cvat/recording-oracle/tests/integration/modules/oracle_webhooks/cron/test_process_exchange_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/integration/modules/oracle_webhooks/cron/test_process_reputation_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/integration/modules/oracle_webhooks/test_webhook_service.py
  packages/examples/cvat/recording-oracle/tests/utils/constants.py
  packages/examples/cvat/recording-oracle/tests/utils/intermediate-results.json
  packages/examples/cvat/recording-oracle/tests/utils/manifest.json
  packages/examples/cvat/recording-oracle/tests/utils/setup_cvat.py
Labels: CVAT

#738 [Job Launcher] Add sendgrid mail service
  packages/apps/job-launcher/server/package.json
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.module.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
  packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.module.ts
  packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.spec.ts
  packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts
  yarn.lock
Labels: Oracles

#796 fix balance calculation and tests
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
Labels: bug, Oracles

#765 [CVAT][Recording Oracle] Add Inter Rater Agreement Measures to Recording Oracle Output
  packages/examples/cvat/recording-oracle/poetry.lock
  packages/examples/cvat/recording-oracle/pyproject.toml
  packages/examples/cvat/recording-oracle/src/modules/agreement/__init__.py
  packages/examples/cvat/recording-oracle/src/modules/agreement/measures.py
  packages/examples/cvat/recording-oracle/src/modules/agreement/utils.py
  packages/examples/cvat/recording-oracle/src/modules/agreement/validations.py
  packages/examples/cvat/recording-oracle/src/modules/webhook/api_schema.py
  packages/examples/cvat/recording-oracle/src/modules/webhook/process_intermediate_results.py
  packages/examples/cvat/recording-oracle/tests/testresources/recording_oracle_dummy_input.json
  packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/conftest.py
  packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/test_measures.py
  packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/test_utils.py
  packages/examples/cvat/recording-oracle/tests/unit/modules/webhook/conftest.py
  packages/examples/cvat/recording-oracle/tests/unit/modules/webhook/test_process_intermediate_results.py
Labels: CVAT, Oracles

#801 [CVAT][AGREEMENT] Add property tests for agreement measures.
  packages/examples/cvat/recording-oracle/dockerfiles/test.Dockerfile
  packages/examples/cvat/recording-oracle/poetry.lock
  packages/examples/cvat/recording-oracle/pyproject.toml
  packages/examples/cvat/recording-oracle/src/agreement/measures.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_measures.py
Labels: CVAT, Agreement Package

#815 Job Launcher - fix bugs of job launcher
  packages/apps/job-launcher/server/src/common/constants/payment.ts
  packages/apps/job-launcher/server/src/common/enums/payment.ts
  packages/apps/job-launcher/server/src/common/utils/decimal.ts
  packages/apps/job-launcher/server/src/common/utils/index.ts
  packages/apps/job-launcher/server/src/database/migrations/1691485394906-InitialMigration.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
  packages/apps/job-launcher/server/src/modules/job/job.controller.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
  packages/apps/job-launcher/server/src/modules/user/user.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: bug, Oracles

#820 Job Launcher - fix crypto payments vulnerability
  packages/apps/job-launcher/server/src/common/config/networks.ts
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/common/utils/decimal.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
Labels: bug, Oracles

#821 Job Launcher - add ssl to db config
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/database/database.module.ts
  packages/apps/job-launcher/server/typeorm.config.ts
Labels: Oracles

#826 Job Launcher - vercel config changes
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/docker-compose.yml
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/database/database.module.ts
  packages/apps/job-launcher/server/src/modules/user/user.service.spec.ts
  packages/apps/job-launcher/server/typeorm.config.ts
Labels: Oracles

#822 [CVAT] [Reputation Oracle] Align with CVAT example's new recording oracle output format.
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/apps/reputation-oracle/server/test/constants.ts
Labels: CVAT, Oracles

#823 [AGREEMENT] Add bootstrapping capabilities to agreement package
  packages/examples/cvat/recording-oracle/dockerfiles/test.Dockerfile
  packages/examples/cvat/recording-oracle/poetry.lock
  packages/examples/cvat/recording-oracle/pyproject.toml
  packages/examples/cvat/recording-oracle/src/agreement/__init__.py
  packages/examples/cvat/recording-oracle/src/agreement/bootstrap.py
  packages/examples/cvat/recording-oracle/src/utils/process_intermediate_results.py
  packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_exchange_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/conftest.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_bootstrap.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_measures.py
Labels: CVAT, Oracles, IRA Package

#839 [Job Launcher] Get valid networks
  packages/apps/job-launcher/server/src/modules/web3/web3.controller.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.module.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
Labels: CVAT

#841 [SDK] Nullable credentials
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/sdk/typescript/human-protocol-sdk/src/storage.ts
  packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts
Labels: SDK

#845 Job Launcher - fix build error
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: bug, Oracles

#846 [Job Launcher] Calculate job bounties
  packages/apps/job-launcher/server/src/common/utils/index.ts
  packages/apps/job-launcher/server/src/modules/job/job.dto.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.test.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: CVAT

#851 [Job Launcher] Job bounties
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: CVAT

#853 Feat: Add JobRequesterId to createEscrow function
  packages/core/README.md
  packages/core/contracts/EscrowFactory.sol
  packages/core/contracts/test/EscrowFactoryV0.sol
  packages/core/test/EscrowFactory.ts
  packages/core/test/RewardPool.ts
  packages/core/test/Staking.ts
  packages/examples/fortune/launcher/server/src/plugins/escrow.ts
  packages/examples/fortune/reputation-oracle/src/services/escrow.test.ts
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
  packages/sdk/python/human-protocol-sdk/test/e2e/test_staking.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py
  packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
  packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
  packages/sdk/typescript/subgraph/schema.graphql
  packages/sdk/typescript/subgraph/src/mapping/EscrowFactory.ts
  packages/sdk/typescript/subgraph/template.yaml
Labels: Core

#855 Job Launcher - fix cron job route
  packages/apps/job-launcher/server/src/modules/job/job.controller.ts
Labels: bug, Oracles
