Repository humanprotocol/human-protocol, pull requests merged in 2023-12, with the labels that each got.

#1299 [Job Launcher] Remove typeorm logs
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/database/database.module.ts
Labels: Oracles

#1295 [Reputation Oracle] Swagger docs
  packages/apps/reputation-oracle/server/src/common/interfaces/index.ts
  packages/apps/reputation-oracle/server/src/common/interfaces/reputation.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
  packages/apps/reputation-oracle/server/src/modules/health/health.controller.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.spec.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.dto.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: Oracles

#1323 Job Launcher - Reenable cron jobs
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: bug

#1293 [Job Launcher] Improve Swagger docs
  packages/apps/job-launcher/server/src/app.controller.ts
  packages/apps/job-launcher/server/src/common/constants/errors.ts
  packages/apps/job-launcher/server/src/common/interfaces/user.ts
  packages/apps/job-launcher/server/src/modules/auth/apikey.repository.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.controller.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
  packages/apps/job-launcher/server/src/modules/health/health.controller.ts
  packages/apps/job-launcher/server/src/modules/job/job.controller.ts
  packages/apps/job-launcher/server/src/modules/job/job.dto.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
  packages/apps/job-launcher/server/src/modules/user/user.controller.ts
  packages/apps/job-launcher/server/src/modules/user/user.dto.ts
  packages/apps/job-launcher/server/src/modules/user/user.service.spec.ts
  packages/apps/job-launcher/server/src/modules/user/user.service.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.controller.ts
Labels: Oracles

#1313 [Job Launcher] Webhook retry policy
  packages/apps/job-launcher/server/docker-compose.yml
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/common/constants/errors.ts
  packages/apps/job-launcher/server/src/common/enums/webhook.ts
  packages/apps/job-launcher/server/src/database/database.module.ts
  packages/apps/job-launcher/server/src/database/migrations/1701702644318-addWebhookTable.ts
  packages/apps/job-launcher/server/src/modules/job/job.module.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.controller.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.dto.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.entity.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.repository.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: Oracles

#1347 [Reputation Oracle ] Decrypt data only when is encrypted
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/test/constants.ts
  packages/sdk/typescript/human-protocol-sdk/src/encryption.ts
  packages/sdk/typescript/human-protocol-sdk/test/encryption.test.ts
Labels: SDK, Oracles

#927 [Job Launcher] Get exchange oracle webhook from KVStore
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/docker-compose.yml
  packages/apps/job-launcher/server/src/common/config/env.ts
  packages/apps/job-launcher/server/src/common/constants/errors.ts
  packages/apps/job-launcher/server/src/common/enums/webhook.ts
  packages/apps/job-launcher/server/src/database/database.module.ts
  packages/apps/job-launcher/server/src/database/migrations/1701702644318-addWebhookTable.ts
  packages/apps/job-launcher/server/src/modules/job/job.module.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.controller.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.dto.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.entity.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.repository.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: On hold

#1359 Job Launcher - Fix import routes
  packages/apps/dashboard/ui/package.json
  packages/apps/job-launcher/client/package.json
  packages/apps/job-launcher/server/src/database/database.module.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/meta-code-verify/package.json
  yarn.lock
Labels: bug

#1355 [SDK] [Typescript] [Python] Gas improvements
  docs/sdk/python/human_protocol_sdk.escrow.escrow_client.md
  docs/sdk/python/human_protocol_sdk.kvstore.kvstore_client.md
  docs/sdk/python/human_protocol_sdk.staking.staking_client.md
  docs/sdk/python/human_protocol_sdk.utils.md
  docs/sdk/typescript/classes/base.BaseEthersClient.md
  docs/sdk/typescript/classes/encryption.Encryption.md
  docs/sdk/typescript/classes/encryption.EncryptionUtils.md
  docs/sdk/typescript/classes/escrow.EscrowClient.md
  docs/sdk/typescript/classes/escrow.EscrowUtils.md
  docs/sdk/typescript/classes/kvstore.KVStoreClient.md
  docs/sdk/typescript/classes/staking.StakingClient.md
  docs/sdk/typescript/classes/statistics.StatisticsClient.md
  docs/sdk/typescript/classes/storage.StorageClient.md
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.controller.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
  packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow/escrow_client.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore/kvstore_client.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking/staking_client.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/escrow/test_escrow_client.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/kvstore/test_kvstore_client.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/staking/test_staking_client.py
  packages/sdk/typescript/human-protocol-sdk/src/base.ts
  packages/sdk/typescript/human-protocol-sdk/src/constants.ts
  packages/sdk/typescript/human-protocol-sdk/src/error.ts
  packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
  packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts
  packages/sdk/typescript/human-protocol-sdk/src/staking.ts
  packages/sdk/typescript/human-protocol-sdk/src/utils.ts
  packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
  packages/sdk/typescript/human-protocol-sdk/test/kvstore.test.ts
  packages/sdk/typescript/human-protocol-sdk/test/staking.test.ts
  packages/sdk/typescript/human-protocol-sdk/test/utils/constants.ts
Labels: SDK

#1380 Reputation Oracle - Wrong param hashStream
  packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
Labels: bug

#1391 Job Launcher - Fix list objects in bucket function
  packages/apps/job-launcher/server/src/common/utils/storage.spec.ts
  packages/apps/job-launcher/server/src/common/utils/storage.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
Labels: bug
