Repository humanprotocol/human-protocol, pull requests merged in 2023-10, with the labels that each got.

#975 [SDK][Agreement] Harmonize Interfaces of Agreement Measures
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/__init__.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/utils.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/validations.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/conftest.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_bootstrap.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_measures.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_utils.py
Labels: SDK, IRA Package

#1000 [SDK][Agreement] Fix value range for measures.
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/bootstrap.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/conftest.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_measures.py
Labels: bug, SDK, IRA Package

#995 Add and endpoint to receive solutions marked as invalid
  packages/apps/fortune/exchange-oracle/server/src/common/config/env.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/s3.ts
  packages/apps/fortune/exchange-oracle/server/src/common/interfaces/job.ts
  packages/apps/fortune/exchange-oracle/server/src/common/utils/storage.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.module.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.module.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts
Labels: Oracles

#895 [Reputation Oracle] Add auth and login
  packages/apps/reputation-oracle/server/.env.example
  packages/apps/reputation-oracle/server/src/app.module.ts
  packages/apps/reputation-oracle/server/src/common/config/env.ts
  packages/apps/reputation-oracle/server/src/common/constants/errors.ts
  packages/apps/reputation-oracle/server/src/common/constants/index.ts
  packages/apps/reputation-oracle/server/src/common/enums/user.ts
  packages/apps/reputation-oracle/server/src/common/guards/index.ts
  packages/apps/reputation-oracle/server/src/common/guards/jwt.auth.ts
  packages/apps/reputation-oracle/server/src/common/interfaces/index.ts
  packages/apps/reputation-oracle/server/src/common/interfaces/user.ts
  packages/apps/reputation-oracle/server/src/common/types/index.ts
  packages/apps/reputation-oracle/server/src/common/types/request.ts
  packages/apps/reputation-oracle/server/src/common/validators/confirm.ts
  packages/apps/reputation-oracle/server/src/common/validators/index.ts
  packages/apps/reputation-oracle/server/src/common/validators/password.ts
  packages/apps/reputation-oracle/server/src/database/database.module.ts
  packages/apps/reputation-oracle/server/src/database/migrations/1694691302615-InitialMigration.ts
  packages/apps/reputation-oracle/server/src/main.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.entity.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.module.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.repository.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
  packages/apps/reputation-oracle/server/src/modules/auth/strategy/index.ts
  packages/apps/reputation-oracle/server/src/modules/auth/strategy/jwt.http.ts
  packages/apps/reputation-oracle/server/src/modules/auth/token.entity.ts
  packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.module.ts
  packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.entity.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.module.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.repository.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/apps/reputation-oracle/server/test/constants.ts
  packages/apps/reputation-oracle/server/tsconfig.json
  packages/apps/reputation-oracle/server/typeorm.config.ts
Labels: Oracles

#1016 [Job Launcher] Verify sender of crypto payment
  packages/apps/job-launcher/server/src/common/guards/signature.auth.ts
  packages/apps/job-launcher/server/src/common/utils/signature.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: Oracles

#959 [Exchange Oracle] Upload solutions file
  packages/apps/fortune/exchange-oracle/server/.env.example
  packages/apps/fortune/exchange-oracle/server/.gitignore
  packages/apps/fortune/exchange-oracle/server/docker-compose.yml
  packages/apps/fortune/exchange-oracle/server/src/common/config/env.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/index.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/s3.ts
  packages/apps/fortune/exchange-oracle/server/src/common/interfaces/job.ts
  packages/apps/fortune/exchange-oracle/server/src/main.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.module.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.module.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/fortune/exchange-oracle/server/test/constants.ts
Labels: Oracles

#977 [Recording Oracle] Download exchange solutions and compare with the already uploaded
  packages/apps/fortune/package.json
  packages/apps/fortune/recording-oracle/.eslintrc
  packages/apps/fortune/recording-oracle/docker-compose.yml
  packages/apps/fortune/recording-oracle/package.json
  packages/apps/fortune/recording-oracle/src/app.controller.ts
  packages/apps/fortune/recording-oracle/src/common/config/s3.ts
  packages/apps/fortune/recording-oracle/src/common/config/validation.ts
  packages/apps/fortune/recording-oracle/src/common/constants/curseWords.ts
  packages/apps/fortune/recording-oracle/src/common/constants/index.ts
  packages/apps/fortune/recording-oracle/src/common/interfaces/job.ts
  packages/apps/fortune/recording-oracle/src/common/utils/curseWords.ts
  packages/apps/fortune/recording-oracle/src/common/utils/webhook.ts
  packages/apps/fortune/recording-oracle/src/main.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.controller.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.controller.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.dto.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.module.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.module.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
  packages/apps/fortune/recording-oracle/test/constants.ts
Labels: Oracles

#1050 [Job Launcher] Add signature to all webhook calls
  packages/apps/job-launcher/server/src/common/enums/role.ts
  packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts
  packages/apps/job-launcher/server/src/common/guards/signature.auth.ts
  packages/apps/job-launcher/server/src/modules/job/job.controller.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: Oracles

#1044 [Exchange Oracle] Add signature to all webhook calls sent and received in Exchange Oracle
  packages/apps/fortune/exchange-oracle/server/src/common/constant/index.ts
  packages/apps/fortune/exchange-oracle/server/src/common/enums/role.ts
  packages/apps/fortune/exchange-oracle/server/src/common/guards/index.ts
  packages/apps/fortune/exchange-oracle/server/src/common/guards/signature.auth.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/common/guards/signature.auth.ts
  packages/apps/fortune/exchange-oracle/server/src/common/utils/signature.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/common/utils/signature.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
  packages/apps/fortune/exchange-oracle/server/test/constants.ts
Labels: Oracles

#1049 [Reputation Oracle] Add signature to all webhook endpoints
  packages/apps/reputation-oracle/server/src/common/enums/role.ts
  packages/apps/reputation-oracle/server/src/common/guards/signature.auth.spec.ts
  packages/apps/reputation-oracle/server/src/common/guards/signature.auth.ts
  packages/apps/reputation-oracle/server/src/common/utils/signature.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.spec.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: Oracles

#1062 [Job Launcher][Reputation Oracle] Add Sendgrid email templates
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
  packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts
  packages/apps/reputation-oracle/server/src/common/constants/index.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
  packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.ts
Labels: Oracles

#1068 [Exchange Oracle] Fix tests
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/test/constants.ts
Labels: Oracles

#1067 [Job Launcher][Reputation Oracle] Fix error with duplicated tokens in auth
  packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
  packages/apps/job-launcher/server/src/modules/auth/token.repository.ts
  packages/apps/reputation-oracle/server/src/common/config/env.ts
  packages/apps/reputation-oracle/server/src/main.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
  packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts
Labels: Oracles

#1083 [Job Launcher] Swagger
  packages/apps/job-launcher/server/src/app.module.ts
  packages/apps/job-launcher/server/src/main.ts
Labels: Oracles

#1087 [SDK][Typescript] Export Encryption and EncryptionUtils
  packages/sdk/typescript/human-protocol-sdk/package.json
  packages/sdk/typescript/human-protocol-sdk/src/index.ts
Labels: SDK

#1104 [Exchange Oracle ] Stop requesting solutions
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
Labels: Oracles

#1109 [Recording Oracle] Include invalid solutions in intermediate results
  packages/apps/fortune/exchange-oracle/server/src/common/interfaces/job.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/fortune/recording-oracle/src/common/enums/job.ts
  packages/apps/fortune/recording-oracle/src/common/interfaces/job.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
Labels: Oracles

#1119 [Reputation Oracle] Create reputation system
  packages/apps/reputation-oracle/server/src/common/enums/job.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/apps/reputation-oracle/server/test/constants.ts
Labels: Oracles

#1126 [Job Launcher] Fix case comparison and obtain partial and paid escrows
  packages/apps/job-launcher/server/src/common/utils/status.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: Oracles

#1128 [Job Launcher] Fix job status and chain id in getJobsList
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
Labels: bug, Oracles

#1132 [Job Launcher] Fix job status in getJobsList add status in job details
  packages/apps/job-launcher/server/src/modules/job/job.dto.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: Oracles

#1142 Hufi - fix swagger static files routes
  packages/apps/hufi/exchange-oracle/server/src/app.module.ts
  packages/apps/hufi/job-launcher/server/src/app.module.ts
  packages/apps/job-launcher/server/src/app.module.ts
Labels: bug

#1147 [Reputation Oracle] Vercel setup
  packages/apps/reputation-oracle/server/package.json
  packages/apps/reputation-oracle/server/vercel.json
Labels: Oracles

#1150 [Reputation Oracle] Remove getBalance check and check number of solutions received
  packages/apps/reputation-oracle/server/src/common/constants/errors.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: Oracles

#1157 Job Luancher - fix allowed status to cancel job
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
Labels: bug, Oracles

#1165 [Reputation Oracle] Storage module
  packages/apps/reputation-oracle/server/src/common/config/index.ts
  packages/apps/reputation-oracle/server/src/common/config/s3.ts
  packages/apps/reputation-oracle/server/src/common/interfaces/s3.ts
  packages/apps/reputation-oracle/server/src/common/utils/index.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.module.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.module.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
  packages/apps/reputation-oracle/server/test/constants.ts
Labels: Oracles
