Repository humanprotocol/human-protocol, pull requests merged in 2024-01, with the labels that each got.

#1449 [SDK] Fix error messages when reverting transactions
  packages/sdk/typescript/human-protocol-sdk/src/utils.ts
Labels: SDK

#1475 Job Launcher Client - Error in Job bounty calculation
  packages/apps/job-launcher/client/src/components/Jobs/Create/schema.ts
Labels: bug

#1144 [CVAT][Oracles] Fix CVAT oracles tests
  packages/examples/cvat/exchange-oracle/.dockerignore
  packages/examples/cvat/exchange-oracle/alembic/versions/16ecc586d685_init.py
  packages/examples/cvat/exchange-oracle/docker-compose.test.yml
  packages/examples/cvat/exchange-oracle/dockerfiles/blockchain-node.Dockerfile
  packages/examples/cvat/exchange-oracle/dockerfiles/test.Dockerfile
  packages/examples/cvat/exchange-oracle/src/crons/state_trackers.py
  packages/examples/cvat/exchange-oracle/tests/api/test_cvat_webhook.py
  packages/examples/cvat/exchange-oracle/tests/api/test_cvat_webhook_api.py
  packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py
  packages/examples/cvat/exchange-oracle/tests/api/test_jl_webhook.py
  packages/examples/cvat/exchange-oracle/tests/api/test_webhook_api.py
  packages/examples/cvat/exchange-oracle/tests/integration/chain/test_escrow.py
  packages/examples/cvat/exchange-oracle/tests/integration/chain/test_kvstore.py
  packages/examples/cvat/exchange-oracle/tests/integration/chain/test_web3.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_retrieve_annotations.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_assignments.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_projects.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_tasks.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_task_creation.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_job_launcher_webhooks.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_recording_oracle_webhooks.py
  packages/examples/cvat/exchange-oracle/tests/integration/cron/test_retrieve_annotations.py
  packages/examples/cvat/exchange-oracle/tests/integration/services/test_cvat.py
  packages/examples/cvat/exchange-oracle/tests/integration/services/test_exchange.py
  packages/examples/cvat/exchange-oracle/tests/integration/services/test_webhook.py
  packages/examples/cvat/exchange-oracle/tests/unit/helpers/test_format_annotations.py
  packages/examples/cvat/exchange-oracle/tests/utils/constants.py
  packages/examples/cvat/exchange-oracle/tests/utils/db_helper.py
  packages/examples/cvat/exchange-oracle/tests/utils/manifest.json
  packages/examples/cvat/exchange-oracle/tests/utils/setup_cvat.py
  packages/examples/cvat/exchange-oracle/tests/utils/setup_escrow.py
  packages/examples/cvat/exchange-oracle/tests/utils/setup_kvstore.py
  packages/examples/cvat/recording-oracle/dockerfiles/blockchain-node.Dockerfile
  packages/examples/cvat/recording-oracle/dockerfiles/test.Dockerfile
  packages/examples/cvat/recording-oracle/src/services/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/chain/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/chain/test_escrow.py
  packages/examples/cvat/recording-oracle/tests/integration/chain/test_kvstore.py
  packages/examples/cvat/recording-oracle/tests/integration/chain/test_web3.py
  packages/examples/cvat/recording-oracle/tests/integration/cron/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_exchange_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_reputation_oracle_webhooks.py
  packages/examples/cvat/recording-oracle/tests/integration/endpoints/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/endpoints/test_webhook.py
  packages/examples/cvat/recording-oracle/tests/integration/services/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/services/cloud/__init__.py
  packages/examples/cvat/recording-oracle/tests/integration/services/cloud/test_client_service.py
  packages/examples/cvat/recording-oracle/tests/integration/services/test_validation_service.py
  packages/examples/cvat/recording-oracle/tests/integration/services/test_webhook_service.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/conftest.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_bootstrap.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_measures.py
  packages/examples/cvat/recording-oracle/tests/unit/agreement/test_utils.py
  packages/examples/cvat/recording-oracle/tests/unit/webhook/conftest.py
  packages/examples/cvat/recording-oracle/tests/unit/webhook/test_process_intermediate_results.py
  packages/examples/cvat/recording-oracle/tests/utils/constants.py
  packages/examples/cvat/recording-oracle/tests/utils/setup_escrow.py
  packages/examples/cvat/recording-oracle/tests/utils/setup_kvstore.py
Labels: bug, CVAT

#1328 [Job Launcher] Decrypt file after downloading
  packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
  packages/apps/job-launcher/server/test/constants.ts
Labels: On hold

#1498 [Job Launcher] Get operator address
  packages/apps/job-launcher/server/src/modules/web3/web3.controller.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
Labels: Fortune

#1505 [Job Launcher] Encryption module
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.module.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
  packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
Labels: Fortune

#1495 [Reputation Oracle] feat: Implement API endpoints for KYC
  packages/apps/reputation-oracle/server/src/app.module.ts
  packages/apps/reputation-oracle/server/src/common/config/env.ts
  packages/apps/reputation-oracle/server/src/common/constants/errors.ts
  packages/apps/reputation-oracle/server/src/common/enums/user.ts
  packages/apps/reputation-oracle/server/src/database/database.module.ts
  packages/apps/reputation-oracle/server/src/database/migrations/1706196712859-AddKycTable.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
  packages/apps/reputation-oracle/server/src/modules/auth/strategy/jwt.http.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.spec.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.dto.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.entity.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.module.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.repository.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.entity.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.module.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Labels: On hold
