Repository humanprotocol/human-protocol, pull requests merged in 2024-09, with the labels that each got.

#2500 [HUMAN App] Fix the role Job Launcher to use upper case
  packages/apps/human-app/frontend/src/smart-contracts/EthKVStore/config.ts
Labels: bug

#2504 [Human App] New version modal
  packages/apps/human-app/frontend/src/components/ui/modal/modal-content.tsx
  packages/apps/human-app/frontend/src/components/ui/modal/modal.store.ts
  packages/apps/human-app/frontend/src/pages/homepage/home.page.tsx
  packages/apps/human-app/frontend/src/pages/homepage/update-version-modal.tsx
Labels: Frontend

#2502 [Dashboard][Server] Preserve historical hCaptcha stats on GCP
  packages/apps/dashboard/server/.env.example
  packages/apps/dashboard/server/src/common/config/config.module.ts
  packages/apps/dashboard/server/src/common/config/env-config.service.ts
  packages/apps/dashboard/server/src/common/config/s3-config.service.ts
  packages/apps/dashboard/server/src/modules/stats/stats.module.ts
  packages/apps/dashboard/server/src/modules/stats/stats.service.ts
  packages/apps/dashboard/server/src/modules/storage/storage.module.ts
  packages/apps/dashboard/server/src/modules/storage/storage.service.ts
Labels: On hold

#2488 Add qualifications in Job Launcher Frontend
  packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx
  packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx
  packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx
  packages/apps/job-launcher/client/src/components/Jobs/Create/schema.ts
  packages/apps/job-launcher/client/src/services/job.ts
  packages/apps/job-launcher/client/src/services/qualification.ts
  packages/apps/job-launcher/client/src/types/index.ts
Labels: Frontend
