Repository humanprotocol/human-protocol, pull requests merged in 2024-06, with the labels that each got.

#2100 Deploy Fortune Exchange and Recording Oracle on Render
  packages/apps/fortune/exchange-oracle/server/src/app.module.ts
  packages/apps/fortune/exchange-oracle/server/src/database/migrations/1717112007469-UpdateAssignment.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.module.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.service.ts
  packages/apps/fortune/recording-oracle/.env.example
  packages/apps/fortune/recording-oracle/src/common/config/env-schema.ts
  packages/apps/fortune/recording-oracle/src/modules/web3/web3.service.spec.ts
  render.yaml
Labels: WIP

#2108 Fix for allowed statuses to cancel a job
  packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
  packages/apps/job-launcher/client/src/types/index.ts
  packages/apps/job-launcher/server/src/common/constants/errors.ts
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/modules/auth/auth.module.ts
  packages/apps/job-launcher/server/src/modules/cron-job/cron-job.module.ts
  packages/apps/job-launcher/server/src/modules/job/job.module.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
  packages/apps/job-launcher/server/src/modules/user/user.module.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts
  packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.module.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Labels: WIP

#2129 Fix sdk docs
  docs/sdk/SUMMARY.md
  docs/sdk/typescript/base/classes/BaseEthersClient.md
  docs/sdk/typescript/encryption/classes/Encryption.md
  docs/sdk/typescript/encryption/classes/EncryptionUtils.md
  docs/sdk/typescript/escrow/classes/EscrowClient.md
  docs/sdk/typescript/escrow/classes/EscrowUtils.md
  docs/sdk/typescript/kvstore/classes/KVStoreClient.md
  docs/sdk/typescript/kvstore/classes/KVStoreUtils.md
  docs/sdk/typescript/modules.md
  docs/sdk/typescript/operator/classes/OperatorUtils.md
  docs/sdk/typescript/staking/classes/StakingClient.md
  docs/sdk/typescript/statistics/classes/StatisticsClient.md
  docs/sdk/typescript/storage/classes/StorageClient.md
  docs/sdk/typescript/transaction/README.md
  docs/sdk/typescript/transaction/classes/TransactionUtils.md
  packages/sdk/typescript/human-protocol-sdk/package.json
Labels: bug

#2164 [Job Launcher][Reputation Oracle] Fix swagger error on Render
  packages/apps/job-launcher/server/src/app.module.ts
  packages/apps/job-launcher/server/src/common/guards/apikey.auth.spec.ts
  packages/apps/job-launcher/server/src/common/guards/apikey.auth.ts
  packages/apps/reputation-oracle/server/src/app.module.ts
Labels: bug

#2180 [Reputation Oracle] Refresh token
  packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts
Labels: bug

#2196 [Exchange Oracle] Transform roles to uppercase
  packages/apps/fortune/exchange-oracle/server/src/common/enums/role.ts
Labels: Fortune

#2202 [Job Launcher] Fix CVAT Job creation
  packages/apps/job-launcher/server/src/common/constants/errors.ts
  packages/apps/job-launcher/server/src/common/utils/storage.ts
  packages/apps/job-launcher/server/src/modules/job/job.service.ts
Labels: bug

#2199 [Subgraph] Remove EscrowStatusEvent from legacy contracts
  packages/sdk/typescript/subgraph/src/mapping/legacy/Escrow.ts
  packages/sdk/typescript/subgraph/src/mapping/legacy/EscrowFactory.ts
  packages/sdk/typescript/subgraph/tests/legacy/escrow-factory/escrow-factory.test.ts
  packages/sdk/typescript/subgraph/tests/legacy/escrow/escrow.test.ts
Labels: bug
