Repository humanprotocol/human-protocol, pull requests merged in 2024-04, with the labels that each got.

#1773 [SDK] Fix reputation network address
  packages/sdk/typescript/human-protocol-sdk/src/operator.ts
Labels: SDK

#1798 [Reputation Oracle] Fixed create incoming webhook method
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Labels: bug

#1802 Fortune local environment
  packages/apps/fortune/exchange-oracle/server/package.json
  packages/apps/fortune/exchange-oracle/server/test/setup.ts
  packages/apps/fortune/recording-oracle/package.json
  packages/apps/fortune/recording-oracle/src/common/constants/networks.ts
  packages/apps/fortune/recording-oracle/src/common/enums/webhook.ts
  packages/apps/fortune/recording-oracle/src/common/utils/webhook.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
  packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
  packages/apps/fortune/recording-oracle/src/modules/webhook/webhook.controller.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/webhook/webhook.dto.ts
  packages/apps/fortune/recording-oracle/src/modules/webhook/webhook.service.spec.ts
  packages/apps/fortune/recording-oracle/test/setup.ts
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts
  packages/apps/job-launcher/server/test/setup.ts
  packages/apps/reputation-oracle/server/package.json
  packages/apps/reputation-oracle/server/src/common/config/networks.ts
  packages/apps/reputation-oracle/server/src/common/constants/errors.ts
  packages/apps/reputation-oracle/server/src/common/constants/index.ts
  packages/apps/reputation-oracle/server/src/common/enums/web3.ts
  packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts
  packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
  packages/apps/reputation-oracle/server/src/modules/web3/web3.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts
  packages/apps/reputation-oracle/server/test/setup.ts
  scripts/Makefile
  scripts/fortune/.env.exco-server
  scripts/fortune/.env.jl-server
  scripts/fortune/.env.rep-oracle
Labels: Fortune

#1804 Fix webhook typo
  packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron.job.controller.ts
  packages/apps/reputation-oracle/server/src/modules/cron-job/cron.job.controller.ts
Labels: bug

#1816 Reputation Oracle - add hcaptcha token to signin dto
  packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
  packages/apps/reputation-oracle/server/test/constants.ts
Labels: bug

#1822 [SDK][Python] Subgraph addresses
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/escrow.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/hmtoken.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/reward.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py
Labels: SDK

#1849 [SDK] Enhance Operator Data
  docs/sdk/python/human_protocol_sdk.constants.md
  docs/sdk/python/human_protocol_sdk.md
  docs/sdk/python/human_protocol_sdk.operator.operator_utils.md
  docs/sdk/typescript/classes/base.BaseEthersClient.md
  docs/sdk/typescript/classes/encryption.Encryption.md
  docs/sdk/typescript/classes/encryption.EncryptionUtils.md
  docs/sdk/typescript/classes/escrow.EscrowClient.md
  docs/sdk/typescript/classes/escrow.EscrowUtils.md
  docs/sdk/typescript/classes/kvstore.KVStoreClient.md
  docs/sdk/typescript/classes/operator.OperatorUtils.md
  docs/sdk/typescript/classes/staking.StakingClient.md
  docs/sdk/typescript/classes/statistics.StatisticsClient.md
  docs/sdk/typescript/classes/storage.StorageClient.md
  packages/apps/job-launcher/server/test/setup.ts
  packages/sdk/python/human-protocol-sdk/example.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/escrow.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/hmtoken.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/operator.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/reward.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/statistics/test_statistics_client.py
  packages/sdk/typescript/human-protocol-sdk/src/constants.ts
  packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/operator.ts
  packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
  packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts
  packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
  packages/sdk/typescript/human-protocol-sdk/test/kvstore.test.ts
  packages/sdk/typescript/human-protocol-sdk/test/operator.test.ts
  packages/sdk/typescript/subgraph/schema.graphql
  packages/sdk/typescript/subgraph/src/mapping/KVStore.ts
Labels: SDK

#1863 Polygon Amoy network deployment
  .github/workflows/cd-deploy-contracts.yaml
  docs/sdk/python/human_protocol_sdk.constants.md
  docs/sdk/python/human_protocol_sdk.escrow.escrow_utils.md
  docs/sdk/python/human_protocol_sdk.md
  docs/sdk/python/human_protocol_sdk.operator.operator_utils.md
  docs/sdk/python/human_protocol_sdk.statistics.statistics_client.md
  docs/sdk/typescript/classes/base.BaseEthersClient.md
  docs/sdk/typescript/classes/encryption.Encryption.md
  docs/sdk/typescript/classes/encryption.EncryptionUtils.md
  docs/sdk/typescript/classes/escrow.EscrowClient.md
  docs/sdk/typescript/classes/escrow.EscrowUtils.md
  docs/sdk/typescript/classes/kvstore.KVStoreClient.md
  docs/sdk/typescript/classes/operator.OperatorUtils.md
  docs/sdk/typescript/classes/staking.StakingClient.md
  docs/sdk/typescript/classes/statistics.StatisticsClient.md
  docs/sdk/typescript/classes/storage.StorageClient.md
  packages/apps/dashboard/admin/config/cron-tasks.ts
  packages/apps/dashboard/admin/package.json
  packages/apps/dashboard/ui/src/components/Faucet/FaucetView.tsx
  packages/apps/dashboard/ui/src/components/Faucet/__tests__/RequestData.test.tsx
  packages/apps/dashboard/ui/src/components/Icons/chains.tsx
  packages/apps/dashboard/ui/src/constants/index.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/networks.ts
  packages/apps/fortune/exchange-oracle/server/src/common/constant/index.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/web3/web3.service.spec.ts
  packages/apps/fortune/recording-oracle/src/common/constants/networks.ts
  packages/apps/job-launcher/client/src/components/Icons/chains.tsx
  packages/apps/job-launcher/client/src/constants/chains.ts
  packages/apps/job-launcher/client/src/main.tsx
  packages/apps/job-launcher/client/src/providers/CreateJobPageUIProvider.tsx
  packages/apps/job-launcher/server/src/common/config/networks.ts
  packages/apps/job-launcher/server/src/common/constants/index.ts
  packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
  packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
  packages/apps/reputation-oracle/server/src/common/config/networks.ts
  packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
  packages/apps/reputation-oracle/server/src/modules/web3/web3.service.spec.ts
  packages/core/.gitignore
  packages/core/.openzeppelin/unknown-80002.json
  packages/core/hardhat.config.ts
  packages/core/scripts/deploy-proxies.ts
  packages/sdk/python/human-protocol-sdk/example.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow/escrow_utils.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/statistics/statistics_client.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/escrow/test_escrow_client.py
  packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/escrow/test_escrow_utils.py
  packages/sdk/typescript/human-protocol-sdk/example/escrow.ts
  packages/sdk/typescript/human-protocol-sdk/example/operator.ts
  packages/sdk/typescript/human-protocol-sdk/src/constants.ts
  packages/sdk/typescript/human-protocol-sdk/src/enums.ts
  packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
  packages/sdk/typescript/human-protocol-sdk/src/operator.ts
  packages/sdk/typescript/human-protocol-sdk/src/statistics.ts
  packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
  packages/sdk/typescript/subgraph/config/amoy.json
  yarn.lock
Labels: WIP

#1881 Dashboard - Fix strapi admin
  packages/apps/dashboard/admin/config/cron-tasks.ts
  packages/apps/dashboard/admin/package.json
Labels: bug

#1913 [Governance] Operate with timestamps
  packages/core/contracts/governance/DAOSpokeContract.sol
  packages/core/contracts/governance/MetaHumanGovernor.sol
  packages/core/contracts/governance/vhm-token/VHMToken.sol
  packages/core/test/DAOSpokeContract.ts
  packages/core/test/GovernanceUtils.ts
  packages/core/test/MetaHumanGovernor.ts
Labels: WIP
