Repository humanprotocol/human-protocol, pull requests merged in 2024-05, with the labels that each got.

#1954 [Job Launcher] RPC urls as env variables
  packages/apps/job-launcher/client/.env.example
  packages/apps/job-launcher/client/src/constants/chains.ts
  packages/apps/job-launcher/client/src/main.tsx
  packages/apps/job-launcher/client/src/vite-env.d.ts
Labels: WIP

#1955 [Job Launcher] use env vars for RPC urls
  packages/apps/job-launcher/client/src/constants/chains.ts
  packages/apps/job-launcher/client/src/constants/index.tsx
Labels: WIP

#1910 [Reputation Oracle] Rework CVAT payouts
  packages/apps/reputation-oracle/server/src/common/dto/result.ts
  packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/payout/payout.service.ts
Labels: CVAT

#1918 [Fortune Recording Oracle] RPC urls as environment variables
  packages/apps/fortune/recording-oracle/.env.example
  packages/apps/fortune/recording-oracle/src/common/config/config.module.ts
  packages/apps/fortune/recording-oracle/src/common/config/env-schema.ts
  packages/apps/fortune/recording-oracle/src/common/config/network-config.service.ts
  packages/apps/fortune/recording-oracle/src/common/constants/networks.ts
  packages/apps/fortune/recording-oracle/src/modules/web3/web3.service.spec.ts
  packages/apps/fortune/recording-oracle/src/modules/web3/web3.service.ts
Labels: Fortune

#1917 [Fortune Exchange Oracle] RPC urls as environment variables
  packages/apps/fortune/exchange-oracle/server/.env.example
  packages/apps/fortune/exchange-oracle/server/src/common/config/config.module.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/env-schema.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/index.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/network-config.service.ts
  packages/apps/fortune/exchange-oracle/server/src/common/config/networks.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/web3/web3.service.spec.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/web3/web3.service.ts
Labels: Fortune

#1580 [OKX] Xlayer testnet Integration
  .github/workflows/cd-subgraph.yaml
  docs/sdk/python/human_protocol_sdk.constants.md
  docs/sdk/python/human_protocol_sdk.md
  docs/sdk/typescript/classes/base.BaseEthersClient.md
  docs/sdk/typescript/classes/encryption.Encryption.md
  docs/sdk/typescript/classes/encryption.EncryptionUtils.md
  docs/sdk/typescript/classes/escrow.EscrowClient.md
  docs/sdk/typescript/classes/escrow.EscrowUtils.md
  docs/sdk/typescript/classes/kvstore.KVStoreClient.md
  docs/sdk/typescript/classes/operator.OperatorUtils.md
  docs/sdk/typescript/classes/staking.StakingClient.md
  docs/sdk/typescript/classes/statistics.StatisticsClient.md
  docs/sdk/typescript/classes/storage.StorageClient.md
  packages/apps/dashboard/admin/config/cron-tasks.ts
  packages/apps/dashboard/admin/package.json
  packages/apps/dashboard/ui/.env.example
  packages/apps/dashboard/ui/src/components/App/App.tsx
  packages/apps/dashboard/ui/src/components/Icons/OkxIcon.tsx
  packages/apps/dashboard/ui/src/components/Icons/chains.tsx
  packages/apps/dashboard/ui/src/components/Icons/index.ts
  packages/apps/dashboard/ui/src/constants/index.ts
  packages/apps/dashboard/ui/src/vite-env.d.ts
  packages/apps/faucet-server/.env.example
  packages/apps/faucet-server/src/constants/networks.ts
  packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts
  packages/apps/job-launcher/client/src/components/Icons/OkxIcon.tsx
  packages/apps/job-launcher/client/src/components/Icons/chains.tsx
  packages/apps/job-launcher/client/src/constants/chains.ts
  packages/apps/job-launcher/server/.env.example
  packages/apps/job-launcher/server/src/common/config/env-schema.ts
  packages/apps/job-launcher/server/src/common/config/network-config.service.ts
  packages/apps/reputation-oracle/server/.env.example
  packages/apps/reputation-oracle/server/src/common/config/env-schema.ts
  packages/apps/reputation-oracle/server/src/common/config/network-config.service.ts
  packages/core/.env.example
  packages/core/hardhat.config.ts
  packages/core/test/Staking.ts
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
  packages/sdk/typescript/human-protocol-sdk/package.json
  packages/sdk/typescript/human-protocol-sdk/src/constants.ts
  packages/sdk/typescript/human-protocol-sdk/src/enums.ts
  packages/sdk/typescript/subgraph/README.md
  packages/sdk/typescript/subgraph/config/xlayer-testnet.json
  packages/sdk/typescript/subgraph/package.json
  yarn.lock
Labels: WIP

#1997 [Faucet] Remove mainnet networks from faucet
  packages/apps/faucet-server/.env.example
  packages/apps/faucet-server/src/constants/networks.ts
  packages/apps/faucet-server/src/index.ts
  yarn.lock
Labels: bug

#2001 [Reputation Oracle] Fix credentialling routes
  packages/apps/reputation-oracle/server/src/database/database.module.ts
  packages/apps/reputation-oracle/server/src/modules/payout/payout.interface.ts
  packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts
  packages/apps/reputation-oracle/server/src/modules/reputation/reputation.interface.ts
Labels: bug

#2058 [Job Launcher] Fix pagination
  packages/apps/job-launcher/client/src/components/Table/index.tsx
  packages/apps/job-launcher/server/src/common/pagination/pagination.dto.ts
Labels: bug
