Repository humanprotocol/human-protocol, pull requests merged in 2024-12, with the labels that each got.

#2879 [Dashboard] Dashboard fixes after subgraph and contract upgrades
  packages/apps/dashboard/server/.env.example
  packages/apps/dashboard/server/src/app.module.ts
  packages/apps/dashboard/server/src/common/config/env-config.service.ts
  packages/apps/dashboard/server/src/common/config/network-config.service.spec.ts
  packages/apps/dashboard/server/src/common/config/network-config.service.ts
  packages/apps/dashboard/server/src/common/utils/constants.ts
  packages/apps/dashboard/server/src/modules/details/details.controller.ts
  packages/apps/dashboard/server/src/modules/details/details.service.ts
  packages/apps/dashboard/server/src/modules/details/dto/details-pagination.dto.ts
  packages/apps/dashboard/server/src/modules/details/dto/leader.dto.ts
  packages/apps/dashboard/server/src/modules/stats/stats.service.ts
  packages/apps/dashboard/ui-2024/.env.example
  packages/apps/dashboard/ui-2024/src/features/Leaderboard/hooks/useDataGrid.tsx
  packages/apps/dashboard/ui-2024/src/helpers/env.ts
  packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableBody.tsx
  packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableHead.tsx
  packages/apps/dashboard/ui-2024/src/services/api/use-leaderboard-details.tsx
  packages/apps/dashboard/ui-2024/src/utils/config/networks.ts
  packages/apps/dashboard/ui-2024/src/utils/hooks/use-wallet-search.ts
  packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/transaction.py
  packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/transaction.ts
  packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
  packages/sdk/typescript/human-protocol-sdk/src/operator.ts
  packages/sdk/typescript/human-protocol-sdk/test/operator.test.ts
Labels: bug

#2896 Allow direct call to complete after bulkPayOut
  packages/core/.openzeppelin/bsc-testnet.json
  packages/core/.openzeppelin/sepolia.json
  packages/core/.openzeppelin/unknown-80002.json
  packages/core/contracts/Escrow.sol
  packages/core/test/Escrow-USDT.ts
  packages/core/test/Escrow.ts
Labels: Contracts

#2902 [Dashboard] Transactions table
  packages/apps/dashboard/server/src/modules/details/details.service.ts
  packages/apps/dashboard/server/src/modules/details/dto/transaction.dto.ts
  packages/apps/dashboard/ui-2024/src/assets/styles/color-palette.ts
  packages/apps/dashboard/ui-2024/src/components/SearchResults/AbbreviateClipboard.tsx
  packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/cells/TransactionTableCellMethod.tsx
  packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableBody.tsx
  packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableHead.tsx
  packages/apps/dashboard/ui-2024/src/services/api/use-transaction-details.tsx
Labels: Frontend
